### ISSUE TITLE
Link to next-list is not working.

### ISSUE THREAD

**Issue by itsidleboy** [misskayth11/list#4]
### **Whats the issue?**

So you are using a project repo because of which when you use `href="/new-list"`

it goes to https://misskayth11.github.io/newlist/

But

It should go to https://misskayth11.github.io/list/newlist/

### **Fix**
To fix it when you link a new folder please put whole link eg-
`href="https://misskayth11.github.io/list/new-list/"`

**Comment by misskayth11** [comment]
I see. thanks for fixing it and teaching how to write issue too!
